// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ServerLibrary.Data;

#nullable disable

namespace ServerLibrary.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BaseLibrary.Entities.Anexos", b =>
                {
                    b.Property<int>("NroAnexo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NroAnexo"));

                    b.Property<int>("Correl")
                        .HasColumnType("int");

                    b.Property<decimal>("Descuento")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("DetalleDocumentoNroDetalleDoc")
                        .HasColumnType("int");

                    b.Property<decimal>("Excento")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("FechaFactura")
                        .HasColumnType("datetime2");

                    b.Property<string>("Glosa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Ice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("Importe")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("Mtoiva")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Nit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NroAutorizacion")
                        .HasColumnType("int");

                    b.Property<int>("NroFactura")
                        .HasColumnType("int");

                    b.Property<int?>("ProveedorCodProv")
                        .HasColumnType("int");

                    b.Property<decimal>("Sujeto")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("TipoEgresoCodTipoEgreso")
                        .HasColumnType("int");

                    b.HasKey("NroAnexo");

                    b.HasIndex("DetalleDocumentoNroDetalleDoc");

                    b.HasIndex("ProveedorCodProv");

                    b.HasIndex("TipoEgresoCodTipoEgreso");

                    b.ToTable("Anexos");
                });

            modelBuilder.Entity("BaseLibrary.Entities.Banco", b =>
                {
                    b.Property<int>("CodBanco")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodBanco"));

                    b.Property<string>("Moneda")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomBanco")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlanCuentaCodCuenta")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("CodBanco");

                    b.HasIndex("PlanCuentaCodCuenta");

                    b.ToTable("Bancos");
                });

            modelBuilder.Entity("BaseLibrary.Entities.Cliente", b =>
                {
                    b.Property<int>("CodCli")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodCli"));

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ClientTypeCodTipoCli")
                        .HasColumnType("int");

                    b.Property<string>("CodigoEx")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Complemento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contacto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedAt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DirCli")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailCli")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FacturarA")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("LimiteCre")
                        .HasColumnType("real");

                    b.Property<string>("NomCli")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NroDoc")
                        .HasColumnType("int");

                    b.Property<string>("PlanCuentaCodCuenta")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TelCli")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoDoc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedAt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserCodUsuario")
                        .HasColumnType("int");

                    b.HasKey("CodCli");

                    b.HasIndex("ClientTypeCodTipoCli");

                    b.HasIndex("PlanCuentaCodCuenta");

                    b.HasIndex("UserCodUsuario");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("BaseLibrary.Entities.Correlativo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Modulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Correlativos");
                });

            modelBuilder.Entity("BaseLibrary.Entities.DetalleDocumento", b =>
                {
                    b.Property<int>("NroDetalleDoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NroDetalleDoc"));

                    b.Property<int>("Correl")
                        .HasColumnType("int");

                    b.Property<int?>("DocumentoNroDoc")
                        .HasColumnType("int");

                    b.Property<string>("Glosa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Mtobd")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("Mtobh")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("Mtodd")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("Mtodh")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("PlanCuentaCodCuenta")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TcCostoCodCc")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NroDetalleDoc");

                    b.HasIndex("DocumentoNroDoc");

                    b.HasIndex("PlanCuentaCodCuenta");

                    b.HasIndex("TcCostoCodCc");

                    b.ToTable("DetalleDocumentos");
                });

            modelBuilder.Entity("BaseLibrary.Entities.Documento", b =>
                {
                    b.Property<int>("NroDoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NroDoc"));

                    b.Property<int?>("BancoCodBanco")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaDoc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("HoraRegistro")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Importe")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Moneda")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NroCheque")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Origen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProveedorCodProv")
                        .HasColumnType("int");

                    b.HasKey("NroDoc");

                    b.HasIndex("BancoCodBanco");

                    b.HasIndex("ProveedorCodProv");

                    b.ToTable("Documentos");
                });

            modelBuilder.Entity("BaseLibrary.Entities.Empresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Logo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Sucursal")
                        .HasColumnType("bit");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Empresas");
                });

            modelBuilder.Entity("BaseLibrary.Entities.Gestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Anho")
                        .HasColumnType("int");

                    b.Property<int>("Mes")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Gestiones");
                });

            modelBuilder.Entity("BaseLibrary.Entities.Grupo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodGrupo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Grupos");
                });

            modelBuilder.Entity("BaseLibrary.Entities.Menu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("IconName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Menus");
                });

            modelBuilder.Entity("BaseLibrary.Entities.MenuItems", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Block")
                        .HasColumnType("int");

                    b.Property<int?>("MenuId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MenuId");

                    b.ToTable("MenuItems");
                });

            modelBuilder.Entity("BaseLibrary.Entities.Nivel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CodNivel")
                        .HasColumnType("int");

                    b.Property<int>("Cuantos")
                        .HasColumnType("int");

                    b.Property<int>("Largo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Niveles");
                });

            modelBuilder.Entity("BaseLibrary.Entities.PlanCuenta", b =>
                {
                    b.Property<string>("CodCuenta")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CreatedAt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Grupo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Moneda")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Nivel")
                        .HasColumnType("int");

                    b.Property<string>("NomCuenta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoCuenta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedAt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CodCuenta");

                    b.ToTable("PlanCuentas");
                });

            modelBuilder.Entity("BaseLibrary.Entities.Proveedor", b =>
                {
                    b.Property<int>("CodProv")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodProv"));

                    b.Property<string>("CodigoEx")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Complemento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contacto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedAt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DirProv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailProv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("LimiteCre")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("NomProv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NroDoc")
                        .HasColumnType("int");

                    b.Property<string>("PlanCuentaCodCuenta")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TelProv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedAt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UsuarioCodUsuario")
                        .HasColumnType("int");

                    b.HasKey("CodProv");

                    b.HasIndex("PlanCuentaCodCuenta");

                    b.HasIndex("UsuarioCodUsuario");

                    b.ToTable("Proveedores");
                });

            modelBuilder.Entity("BaseLibrary.Entities.RefreshTokenInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Token")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("RefreshTokenInfos");
                });

            modelBuilder.Entity("BaseLibrary.Entities.SystemPermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MenuId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SystemPermissions");
                });

            modelBuilder.Entity("BaseLibrary.Entities.SystemRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SystemRoles");
                });

            modelBuilder.Entity("BaseLibrary.Entities.TcCosto", b =>
                {
                    b.Property<string>("CodCc")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NomCc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomResp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CodCc");

                    b.ToTable("TcCostos");
                });

            modelBuilder.Entity("BaseLibrary.Entities.TipoCliente", b =>
                {
                    b.Property<int>("CodTipoCli")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodTipoCli"));

                    b.Property<decimal?>("Discount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("NomTipoCli")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CodTipoCli");

                    b.ToTable("TipoClientes");
                });

            modelBuilder.Entity("BaseLibrary.Entities.TipoDoc", b =>
                {
                    b.Property<int>("CodTipoDoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodTipoDoc"));

                    b.Property<string>("NomTipoDoc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CodTipoDoc");

                    b.ToTable("TipoDocs");
                });

            modelBuilder.Entity("BaseLibrary.Entities.TipoEgreso", b =>
                {
                    b.Property<int>("CodTipoEgreso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodTipoEgreso"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlanCuentaCodCuenta")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("CodTipoEgreso");

                    b.HasIndex("PlanCuentaCodCuenta");

                    b.ToTable("TipoEgresos");
                });

            modelBuilder.Entity("BaseLibrary.Entities.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("BaseLibrary.Entities.Usuario", b =>
                {
                    b.Property<int>("CodUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodUsuario"));

                    b.Property<string>("CreatedAt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedAt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CodUsuario");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("BaseLibrary.Entities.Anexos", b =>
                {
                    b.HasOne("BaseLibrary.Entities.DetalleDocumento", "DetalleDocumento")
                        .WithMany("Anexos")
                        .HasForeignKey("DetalleDocumentoNroDetalleDoc");

                    b.HasOne("BaseLibrary.Entities.Proveedor", "Proveedor")
                        .WithMany("Anexos")
                        .HasForeignKey("ProveedorCodProv");

                    b.HasOne("BaseLibrary.Entities.TipoEgreso", "TipoEgreso")
                        .WithMany("Anexos")
                        .HasForeignKey("TipoEgresoCodTipoEgreso");

                    b.Navigation("DetalleDocumento");

                    b.Navigation("Proveedor");

                    b.Navigation("TipoEgreso");
                });

            modelBuilder.Entity("BaseLibrary.Entities.Banco", b =>
                {
                    b.HasOne("BaseLibrary.Entities.PlanCuenta", "PlanCuenta")
                        .WithMany("Bancos")
                        .HasForeignKey("PlanCuentaCodCuenta");

                    b.Navigation("PlanCuenta");
                });

            modelBuilder.Entity("BaseLibrary.Entities.Cliente", b =>
                {
                    b.HasOne("BaseLibrary.Entities.TipoCliente", "ClientType")
                        .WithMany("Clientes")
                        .HasForeignKey("ClientTypeCodTipoCli");

                    b.HasOne("BaseLibrary.Entities.PlanCuenta", "PlanCuenta")
                        .WithMany("Clientes")
                        .HasForeignKey("PlanCuentaCodCuenta");

                    b.HasOne("BaseLibrary.Entities.Usuario", "User")
                        .WithMany("Clientes")
                        .HasForeignKey("UserCodUsuario");

                    b.Navigation("ClientType");

                    b.Navigation("PlanCuenta");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BaseLibrary.Entities.DetalleDocumento", b =>
                {
                    b.HasOne("BaseLibrary.Entities.Documento", "Documento")
                        .WithMany("DetalleDocumentos")
                        .HasForeignKey("DocumentoNroDoc");

                    b.HasOne("BaseLibrary.Entities.PlanCuenta", null)
                        .WithMany("DetalleDocumentos")
                        .HasForeignKey("PlanCuentaCodCuenta");

                    b.HasOne("BaseLibrary.Entities.TcCosto", "TcCosto")
                        .WithMany("DetalleDocumentos")
                        .HasForeignKey("TcCostoCodCc");

                    b.Navigation("Documento");

                    b.Navigation("TcCosto");
                });

            modelBuilder.Entity("BaseLibrary.Entities.Documento", b =>
                {
                    b.HasOne("BaseLibrary.Entities.Banco", "Banco")
                        .WithMany("Documentos")
                        .HasForeignKey("BancoCodBanco");

                    b.HasOne("BaseLibrary.Entities.Proveedor", "Proveedor")
                        .WithMany("Documentos")
                        .HasForeignKey("ProveedorCodProv");

                    b.Navigation("Banco");

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("BaseLibrary.Entities.MenuItems", b =>
                {
                    b.HasOne("BaseLibrary.Entities.Menu", "Menu")
                        .WithMany("MenuItemsList")
                        .HasForeignKey("MenuId");

                    b.Navigation("Menu");
                });

            modelBuilder.Entity("BaseLibrary.Entities.Proveedor", b =>
                {
                    b.HasOne("BaseLibrary.Entities.PlanCuenta", "PlanCuenta")
                        .WithMany("Proveedores")
                        .HasForeignKey("PlanCuentaCodCuenta");

                    b.HasOne("BaseLibrary.Entities.Usuario", "Usuario")
                        .WithMany("Proveedores")
                        .HasForeignKey("UsuarioCodUsuario");

                    b.Navigation("PlanCuenta");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("BaseLibrary.Entities.TipoEgreso", b =>
                {
                    b.HasOne("BaseLibrary.Entities.PlanCuenta", "PlanCuenta")
                        .WithMany("TipoEgresos")
                        .HasForeignKey("PlanCuentaCodCuenta");

                    b.Navigation("PlanCuenta");
                });

            modelBuilder.Entity("BaseLibrary.Entities.Banco", b =>
                {
                    b.Navigation("Documentos");
                });

            modelBuilder.Entity("BaseLibrary.Entities.DetalleDocumento", b =>
                {
                    b.Navigation("Anexos");
                });

            modelBuilder.Entity("BaseLibrary.Entities.Documento", b =>
                {
                    b.Navigation("DetalleDocumentos");
                });

            modelBuilder.Entity("BaseLibrary.Entities.Menu", b =>
                {
                    b.Navigation("MenuItemsList");
                });

            modelBuilder.Entity("BaseLibrary.Entities.PlanCuenta", b =>
                {
                    b.Navigation("Bancos");

                    b.Navigation("Clientes");

                    b.Navigation("DetalleDocumentos");

                    b.Navigation("Proveedores");

                    b.Navigation("TipoEgresos");
                });

            modelBuilder.Entity("BaseLibrary.Entities.Proveedor", b =>
                {
                    b.Navigation("Anexos");

                    b.Navigation("Documentos");
                });

            modelBuilder.Entity("BaseLibrary.Entities.TcCosto", b =>
                {
                    b.Navigation("DetalleDocumentos");
                });

            modelBuilder.Entity("BaseLibrary.Entities.TipoCliente", b =>
                {
                    b.Navigation("Clientes");
                });

            modelBuilder.Entity("BaseLibrary.Entities.TipoEgreso", b =>
                {
                    b.Navigation("Anexos");
                });

            modelBuilder.Entity("BaseLibrary.Entities.Usuario", b =>
                {
                    b.Navigation("Clientes");

                    b.Navigation("Proveedores");
                });
#pragma warning restore 612, 618
        }
    }
}
